### ISSUE TITLE
Bug in adding mints

### ISSUE THREAD

**Issue by IliaCurtoPelle** [leemordechai/FLAME#12]
Ilia Curto Pelle:
I attempted to add a new mint today by the regular procedure. I added the ancient and modern names and the coordinates, taken from the GPS coordinate website that we are using. However, when I clicked "save", I got an error message saying "Failed to add new Location" I retried a couple of times, but with no success. Let me know if you would want me to do a short video to demonstrate the problem.

**Comment by leemordechai** [comment]
Thanks Ilia, I tried and have the same issue - raised to the developer.

**Comment by IliaCurtoPelle** [comment]
Issue has been resolved.

**Comment by leemordechai** [comment]
Yes - bug fixed!
