### ISSUE TITLE
New finds added successfully, not popping up in list of finds

### ISSUE THREAD

**Issue by pyzmark** [leemordechai/FLAME#13]
Pretty basic procedure to recreate this one. Open the "new find" page, fill in the details, and hit "save". It reports success, but when you check the list of finds, there is no new find.

I can make a video, but this is pretty self explanatory. Let me know if this really will help though.

**Comment by leemordechai** [comment]
raised to developer

**Comment by pyzmark** [comment]
This now seems to be working.

**Comment by leemordechai** [comment]
Yes - bug fixed!
