### ISSUE TITLE
Existing finds cannot be updated (specifically LatLong coords)

### ISSUE THREAD

**Issue by pyzmark** [leemordechai/FLAME#14]
Geographic coordinates were not able to be updated (see video). I tried to update another field (Excavation end date) and it was successful, so this does not affect all fields.

https://user-images.githubusercontent.com/28210739/118878346-b1b13b00-b8ac-11eb-9b34-857a019bf0e4.mp4

**Comment by leemordechai** [comment]
raised to developer

**Comment by leemordechai** [comment]
fixed, and edited the specific entry you showed in the video according to the long/lat you tried to change @pyzmark
