### ISSUE TITLE
URL given in "details" does not match what pops up in another browser window

### ISSUE THREAD

**Issue by pyzmark** [leemordechai/FLAME#15]
I try to recreate a search by copying and pasting the URL from 'details' into a new window. [Now, the video shows another problem, which is that no search resolves in the same browser when I do this. But this is not the bug itself.] The bug itself comes when I paste the URL into Safari (another browser) and it pops up, highlighted by metal. So this suggests that something is not connecting, since the URL itself specifies "MintFocusColorByMetal=False".

https://user-images.githubusercontent.com/28210739/118882119-0eaef000-b8b1-11eb-8f46-9e541e951db6.mp4

**Comment by leemordechai** [comment]
raised to developer
