### ISSUE TITLE
PAS mint attribution not showing up on map tool

### ISSUE THREAD

**Issue by pyzmark** [leemordechai/FLAME#16]
First, it is worth saying that PAS themselves have not handled this hoard properly (https://finds.org.uk/database/hoards/record/id/878), as the original source actually provides 1,622 mint attributions for these coins (p. 216 of:  https://www.jstor.org/stable/42680623). However, they do list one link for one coin (to Rome) on the webpage. This does not show up on the webtool.

![image](https://user-images.githubusercontent.com/28210739/118895039-a23cec80-b8c2-11eb-8d10-2357669b14ec.png)

**Comment by leemordechai** [comment]
Yes, PAS has many such issues as well... But actually our import of their data is correct in this case, the single coin from Rome is 317-318 CE so shouldn't be displayed in our webtool. @pyzmark : close/comment further

**Comment by leemordechai** [comment]
@pyzmark please revisit & let's discuss in our meeting if necessary

**Comment by pyzmark** [comment]
Sure, confirmed. I will look at this again today.

**Comment by pyzmark** [comment]
Yep, having reviewed, the single coin that has a mint attributed to it is prior to our time period. Confirmed and closed.
