### ISSUE TITLE
Custom region search URL does not preserve polygon of region

### ISSUE THREAD

**Issue by pyzmark** [leemordechai/FLAME#19]
This is perhaps not a bug. When you save an URL of a custom region search, it preserves the relevant finds and displays them on the basemap, like so: https://bit.ly/2RWEcdT

However, it does not preserve the outline of the polygon that produced that selection: https://twitter.com/FLAMECoinage/status/1400170421358456832

Is there a way to preserve this artifact, or is this just too much to expect from a URL link?

**Comment by leemordechai** [comment]
@pyzmark This is resolved now - the URL simply preserves the ID number of the search (across users I think) rather than all the variables, See for example: http://csla100w.princeton.edu:82/?PreviousSearchID=1994

Closing this issue - reopen if necessary.
