### ISSUE TITLE
Coin groups with coins beyond the 325-750 range

### ISSUE THREAD

**Issue by IliaCurtoPelle** [leemordechai/FLAME#20]
Hello,
Currently, clicking on the error type "Coin groups with coins beyond the 325-750 range" brings up a list of individual coin groups. However, this does not allow me to go back to the original coin find to compare the dates given in its "find details" with the years in the coin group. In situations where there is a discrepancy or a blatant mistake in the coin group (e.g. 6800 instead of 680 being indicated as a date), I would ideally want to go back to the source material to make sure what the correct dates are. Therefore, creating a button "coin find" that can lead me back to the coin group would be incredibly helpful in my work on these bugs in our database. For reference and for a coding example, please see the button that appears in the  "Coin groups without associated mints" error type.
Best,
Ilia

**Comment by leemordechai** [comment]
noting that this was raised to the developer

**Comment by leemordechai** [comment]
Fixed - you can now access the Coin Find from the same table. 

Closing this issue as it's been resolved.
