### ISSUE TITLE
CSV export - column titles export with a space preceding them

### ISSUE THREAD

**Issue by pyzmark** [leemordechai/FLAME#24]
Possibly a problem about CSV export. I was having problem adapting the data of the groups export while trying to script. Unexplained errors, etc. I did some digging, and it stems from the column titles being exported with a space before them. Instead of “Mint”, we are exporting ” Mint”. So this will be confusing for users. Can we make sure that column titles have no unwanted spaces? In the pictured example ‘BG’ stands for British Groups.
![image](https://user-images.githubusercontent.com/28210739/133006203-6a65e09b-6a31-4785-8b6f-f3a6daa45670.png)

**Comment by leemordechai** [comment]
raised to developer
