### ISSUE TITLE
Add users' username or real name to reference, as appears on CircMod map

### ISSUE THREAD

**Issue by pyzmark** [leemordechai/FLAME#25]
We currently publish the username (sans URL) from the user's white-listed username to identify them. This doesn't do a good job of identifying individuals, especially if they have a self-chosen Gmail (e.g., palemoonfire2187@geocities.com). Since authors may eventually want to claim credit for their particular entries, I think it's important that we decide on a way of allowing them to fill in identifying information in a way that suits them.

Can this be added as a field on their side (or, I suppose, on ours?) on the FLAME site?

**Comment by leemordechai** [comment]
raised to developer (defined as low priority for now)

**Comment by leemordechai** [comment]
fixed
