### ISSUE TITLE
Search issue - Unicode accent characters elude search

### ISSUE THREAD

**Issue by pyzmark** [leemordechai/FLAME#26]
A note about search on the map and different unicode characters. Huda recently emailed me asking if we could insert the mint of Istakhr (formerly Persepolis). I said yes, but looked this up. Indeed, there is no Istakhr. But when you search Persepolis, there is an Iṣṭaḵr. Now, the problem is pretty clearly the specificity of search for unicode characters like ḵ
(i.e., LATIN SMALL LETTER K WITH LINE BELOW Unicode: U+1E35, UTF-8: E1 B8 B5), which is not the same as “k”.

Is there a way to account for this? There must be some standard library of unicode code substitutions, allowing search to tell that k and ḵ are often used interchangeably.

**Comment by leemordechai** [comment]
this has been with the developer since late Oct.
