### ISSUE TITLE
URGENT: Database log-in error

### ISSUE THREAD

**Issue by IliaCurtoPelle** [leemordechai/FLAME#28]
I receive the following message when I try to log in to teh FLAME Admin Panel:
Authorization Error
Error 400: invalid_request

You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy for keeping apps secure.

You can let the app developer know that this app doesn't comply with one or more Google validation rules.

**Comment by pyzmark** [comment]
This has now been resolved. I am closing, unless there are objections.
