### ISSUE TITLE
Complex searches break the "previous search" function

### ISSUE THREAD

**Issue by pyzmark** [leemordechai/FLAME#29]
It took several tries to recreate this. I initially thought it was too many mints (this eventually just stops showing them but retains format). If you select too many categories of search, it forces the "details/re-run/delete" options offscreen. You wind up with a "previous search" field that no longer functions properly, as per the second image.

![image](https://user-images.githubusercontent.com/28210739/138307526-ae4cf5c1-efe1-4cac-bb5c-abb795ae121a.png)

![image](https://user-images.githubusercontent.com/28210739/138307592-fa2eac55-89be-40bf-a452-a41a3fd5c177.png)

**Comment by leemordechai** [comment]
raised to developer

**Comment by leemordechai** [comment]
resolved & closing issue
