### ISSUE TITLE
"Denominations" field on map does not update selection when typing in desired value 

### ISSUE THREAD

**Issue by pyzmark** [leemordechai/FLAME#3]
The denomination search field does not actually seem to filter denominations as you type in parts of the search. So, as you go for 5 nummi, you can type each element of the search and the results remain the same---you have to scroll down to find your entry.
![image](https://user-images.githubusercontent.com/28210739/107567256-c772de00-6ba2-11eb-82ff-e05aa8702451.png)

**Comment by leemordechai** [comment]
raised to developer

**Comment by leemordechai** [comment]
fixed
