### ISSUE TITLE
Some British coin finds not included in the British polygon for bias essay attribution

### ISSUE THREAD

**Issue by pyzmark** [leemordechai/FLAME#30]
This find (see image), as well as several others on the Isles of Scilly (https://en.wikipedia.org/wiki/Isles_of_Scilly) are not associated with the United Kingdom for the purposes of attributing a regional bias essay to them. Thus, while "mainland" British finds have a link to the essay by Rory Naismith on this topic, these do not. We might need to modify the polygon, or find one to cover this case. It may also affect other British Isles, so this will be worth keeping an eye out for and thinking of a scalable solution.

Here is the link for this specific find: http://csla100w.princeton.edu:82/?PreviousSearchID=2644

![image](https://user-images.githubusercontent.com/28210739/139085187-18b3a87c-3f02-4ef1-aa72-7a8bdf356431.png)

**Comment by leemordechai** [comment]
this has been under discussion for well over a month at this point. There are currently some 350 finds in the database which do not belong to any modern country. Will update once this issue is re/solved.

**Comment by pyzmark** [comment]
This now seems to be fixed (see image below). The new polygons are far far more detailed, and it seems as though they are capturing all of the finds we need them to. I am going to close this issue, unless there are further problems.

<img width="950" alt="image" src="https://user-images.githubusercontent.com/28210739/166811046-721d0814-4f4a-4f81-9b4d-af5686b7f0e8.png">
