### ISSUE TITLE
E+ status users cannot add new finds or groups (button does not appear)

### ISSUE THREAD

**Issue by pyzmark** [leemordechai/FLAME#32]
User is EditorPlus status. Is this a problem of reclassification of the E+ classification?

https://user-images.githubusercontent.com/28210739/141489382-68d9cd34-a7e4-4f7e-bdf8-27a8f1a6e721.mp4

**Comment by pyzmark** [comment]
This does seem to be related to the EditorPlus status, as another user with E+ reports they cannot add new finds or groups. They also cannot see the full list of CoinFinds/Groups, which E+ status used to give access to. So can we check out whether there has been some reset? It seems that E+ users have been downgraded to Guests.

**Comment by leemordechai** [comment]
raised to developer

**Comment by leemordechai** [comment]
resolved so I'm closing this issue, let me know if it persists somehow
