### ISSUE TITLE
Date range text bar still breaks in two ways (numbers typed after 325; hyphen after 750)

### ISSUE THREAD

**Issue by pyzmark** [leemordechai/FLAME#33]
I was trying to break the date range bar and these came up. They are theoretically fixed by just reloading the app (or even by manually typing the range back in). For this reason, this may not be a top priority.

https://user-images.githubusercontent.com/28210739/146256844-31d51a4d-22f7-43a7-a68a-a79e99212c7c.mp4

**Comment by leemordechai** [comment]
thanks - raised to developer

**Comment by leemordechai** [comment]
Fixed and tested - @pyzmark please check as well and close the issue if you agree it has been resolved.
