### ISSUE TITLE
Can the header row for the list of coin finds follow as the user scrolls down?

### ISSUE THREAD

**Issue by pyzmark** [leemordechai/FLAME#34]
If you have a sufficiently long list of coin finds, the header (indicating what kind of coins—gold, etc.) is left behind at the top. It would be a nice quality-of-life improvement for the header to follow the user down as they scroll. If this can be done with minimal performance loss, it should be.

https://user-images.githubusercontent.com/28210739/146598944-3b6482ab-7d1f-46a5-a898-4cd1a527a6db.mp4

**Comment by leemordechai** [comment]
Our table does not support this; while it is fixable, it seems like this would take too long to develop.
