### ISSUE TITLE
Cannot delete mints - "an error occurred while processing your request"

### ISSUE THREAD

**Issue by pyzmark** [leemordechai/FLAME#41]
While talking to Ilia we concluded that the very first in our list of mints is probably not a meaningful place. It does not have any coin groups attached to it. However, when I try to delete it, I cannot. Is there something wrong with this function?

![image](https://user-images.githubusercontent.com/28210739/166555020-6be140ce-052b-4b23-8724-eae09fa4d959.png)

![image](https://user-images.githubusercontent.com/28210739/166555025-841cd5a9-b607-43f4-b973-57450469d003.png)

**Comment by leemordechai** [comment]
raised to developer
