### ISSUE TITLE
Substantial delays in chaning information in coin groups

### ISSUE THREAD

**Issue by IliaCurtoPelle** [leemordechai/FLAME#42]
Dear developer,
I hope this finds you well. I wanted to write to report on an issue that is slowing my work down substantially. Let us suppose I create a find and then move on to add coin groups to the find. Under timed conditions, starting from the moment I hit the "Save" button, it takes me 5 seconds to add a new coin group. To edit an already existing coin group, changing any single parameter, it takes me 1 minute and 36 seconds and the same amount of time to delete an already existing coin group. This is a substantial slowdown to my work process. 
Best,
Ilia

**Comment by pyzmark** [comment]
@IliaCurtoPelle, has there been any improvement? Should we close this issue—or is there a compelling reason to keep it open?

**Comment by IliaCurtoPelle** [comment]
I believe we can close it. Performance has improved drastically.

**Comment by pyzmark** [comment]
Great, closing with this comment then.
