### ISSUE TITLE
Coin Groups not being summarized when finds are filtered by modern country

### ISSUE THREAD

**Issue by pyzmark** [leemordechai/FLAME#43]
If you select a modern country in Basic Search, the system correctly filters for finds within the polygon of that country. However, try to summarize those finds' coin groups, and the filtration does not seem to apply. Rather ALL finds are listed.

The video's audio was not captured, but what happens is pretty plain. Notice that total coin numbers at the end for "unknown" mints are in the 200k range. This is not possible for Ukraine alone.

https://user-images.githubusercontent.com/28210739/167756585-18917ba5-a90e-4f67-9e9e-80b7e31ab3f3.mp4

**Comment by leemordechai** [comment]
fixed
