### ISSUE TITLE
Navigating the back-end data by Find NUMBER, not just name

### ISSUE THREAD

**Issue by pyzmark** [leemordechai/FLAME#44]
You can search and sort coin finds by name, etc., but the coin find number (the unique identifier of that find, as opposed to others, which is available in the data dump, but not elsewhere) is not even visible. I would like this to be visible, sortable, and searchable (though not editable, of course), as this would simplify certain verification tasks that we have set for ourselves in other areas of the project (checking the coin finds for doubled entries, for instance).

**Comment by leemordechai** [comment]
raised to developer

**Comment by leemordechai** [comment]
resolved
