### ISSUE TITLE
Is it necessary to run a search to view coin finds in the Layers tab?

### ISSUE THREAD

**Issue by pyzmark** [leemordechai/FLAME#47]
I would like to view all coin finds, as per the Coin Finds button on the Layers tab. But the system tells me I should run a search first. I am pretty sure this was not the case earlier (when this was a static image, I assume). While I assume there are performance or technical reasons for this, I don't think this is a very good experience for users. 

Without the user having run a search, if this button is selected, can a search be run automatically (a search with no parameters, returning all finds)? And if there is a performance issue, can some selection be made arbitrarily, with the system informing the user that some finds are being excluded until they specify further search parameters? I think this would be a better experience, rather than the abrupt instruction to run a search first (the reasons for which are not explained).

<img width="1380" alt="image" src="https://user-images.githubusercontent.com/28210739/175081112-624b73a8-35d8-4ecc-bf7f-af159949025d.png">

**Comment by leemordechai** [comment]
@pyzmark I think this has been fixed - please verify.

**Comment by pyzmark** [comment]
I was going to close this, but while the search turns up clusters onscreen, it does not return coin finds in the left-hand panel (see image)

<img width="1379" alt="image" src="https://user-images.githubusercontent.com/28210739/203365157-00e60a9f-2424-4496-8506-7f1fc71f21ff.png">
