### ISSUE TITLE
Coin find points in the Layers tab are effectively invisible under certain conditions due to color - we should change this

### ISSUE THREAD

**Issue by pyzmark** [leemordechai/FLAME#48]
See image below. Green does not work on the light map, and it does not work on the dark map either (at least, when the finds are within the borders of the modern nation polygon or a custom made polygon). I suggest we change them to something like purple, which will show up on both maps. This probably needs to happen in conjunction with a broader UI redesign (since it will need to be done with cluster color in mind, etc.), but for now this would be a painless fix of this problem.

![image](https://user-images.githubusercontent.com/28210739/175085639-0175e6e8-ded7-40b7-8705-39bd4b28bf0d.png)

**Comment by leemordechai** [comment]
it is now possible to re-define colors in the Admin Panel. Closing issue for now.
![image](https://user-images.githubusercontent.com/16713928/202733652-28252ded-a388-4e69-9bd8-80ecefbcf761.png)
