### ISSUE TITLE
We still cannot delete mints

### ISSUE THREAD

**Issue by pyzmark** [leemordechai/FLAME#49]
Trying to do so throws this error. I tried to delete one of the mints with ? as its name.

<img width="1166" alt="image" src="https://user-images.githubusercontent.com/28210739/175363450-5fb0fc5c-26cc-4fb8-9790-641812d3dac2.png">

**Comment by pyzmark** [comment]
Has this been addressed? I think this is now possible.

**Comment by leemordechai** [comment]
resolved
