### ISSUE TITLE
Coin groups without associated mints bug

### ISSUE THREAD

**Issue by IliaCurtoPelle** [leemordechai/FLAME#5]
Dear all,
I hope this finds you well and healthy. I am writing to report on a bug that I encountered while working on the reports with the error "coin groups without associated mints." These are supposed to be linked with their respective coin finds via the "coin finds" button, but, for about 75-100 of them, there seems to be an issue. When I click on them, I just see a blank page that says "bad request." Please find attached a video of the bug and I would be thankful for any advice to resolve the issue:
https://drive.google.com/file/d/1C1Hc_5-70W6hjyQ6DqpNtRBdTiSiAQAf/view?usp=sharing
With respect,
Ilia Curto Pelle

**Comment by leemordechai** [comment]
Thanks Ilia - passed on to the developer, will update here.

**Comment by leemordechai** [comment]
The reason for this was that these Coin Groups didn't have an associated Coin Find (so appeared in that bug category as well).
This has been resolved - now the link 'Coin Find' doesn't appear in any Coin Group that doesn't have an associated Coin Find.

**Comment by leemordechai** [comment]
(the Coin Groups without associated Coin Finds should likely be resolved before assigning mints)
