### ISSUE TITLE
There seem to be no "strict" or "loose" finds from External Datasets

### ISSUE THREAD

**Issue by pyzmark** [leemordechai/FLAME#50]
The problem is in the subject line. Here is how I found it. I did two pairs of searches. 

1. With "strict" enabled: The first was a search of all finds, with all datasets EXCEPT the core dataset (2,489 coin finds). The second included ONLY core data (2,574 coin finds).
2. With "loose" enabled: Same search, with the first being all datasets EXCEPT core (2,849 coin finds). Notice that number did not change. But the search that included ONLY core data did (3,889 coin finds).

So what is going on here? Is this the result of our core dataset receiving the "vague time" designation at either the find or the group levels (something that imported datasets will not have and we will have no way of assigning)? If it is, is this something we need to think about, in terms of a structural asymmetry in our data? If no one is doing this kind of mediation on their end, are we creating problems for data compatibility and also over-complicating our user interface to include this in the app?

**Comment by leemordechai** [comment]
Yes, the vague definition is ours and is/was our way to attempt to correct for the uncertainty in the source material, i.e. the scholarly publications we've used. Not sure we can do much about this but maybe put a note in the documentation?

**Comment by pyzmark** [comment]
Yes, I can do that. I am going to create a new Label for such work (Documentation), and hopefully this will serve as a to-do list for such matters. What do you think?

**Comment by leemordechai** [comment]
Sure, and please also comment on that in the project documentation that we make accessible on the website..

**Comment by pyzmark** [comment]
Right, so I will document the issue described. For your second point, you mean make clear that issues of documentation, etc. are tracked on Github and should be reported there?

**Comment by leemordechai** [comment]
We can direct users here - I guess there's nothing to lose for doing that. But revising the documentation to clarify the strict/loose issue is most important for this issue. Once you revise the documentation, please close this comment.

**Comment by pyzmark** [comment]
Done. This is now documented.
