### ISSUE TITLE
Opacity on the search panel may not be high enough

### ISSUE THREAD

**Issue by pyzmark** [leemordechai/FLAME#51]
This is especially apparent when using the light colored maps, like Pelagios. Take a look. What do you think?

<img width="1383" alt="image" src="https://user-images.githubusercontent.com/28210739/181614842-84a789a3-6d35-4566-a1b2-b77729744e50.png">

**Comment by leemordechai** [comment]
agree, we'll change it - raised to developer

**Comment by leemordechai** [comment]
resolved, opacity is now 95% (compared to 85% earlier)
