### ISSUE TITLE
"Resources and PDFs" section of website points to 404 error

### ISSUE THREAD

**Issue by pyzmark** [leemordechai/FLAME#52]
Selecting "resources and PDFs" from "General Data" on our backend, as below:

![image](https://user-images.githubusercontent.com/28210739/181634010-3df63efd-25e5-4aaf-b024-cc7ebd774699.png)

It yields a 404 error, as below:

![image](https://user-images.githubusercontent.com/28210739/181634040-54e289a5-c95e-4058-9661-c5fd604047e8.png)

**Comment by leemordechai** [comment]
resolved
