### ISSUE TITLE
When you select a country, subsequent filters added on top of it seem to negate the country filter, or vice versa

### ISSUE THREAD

**Issue by pyzmark** [leemordechai/FLAME#53]
this search indicates that if you select a country to start, your subsequent filter choices will not be implemented. Thus, coins on Ukrainian territory, and they are supposed to be only gold coins, but you can see others are included: http://csla100w.princeton.edu:82/?PreviousSearchID=8946

Likewise if you select filter options after a country search, the filter returns results for the whole map, although the modern country remains highlighted on the map.

**Comment by leemordechai** [comment]
raised to developer

**Comment by leemordechai** [comment]
fixed and closed.
