### ISSUE TITLE
Metals are filtered out in "summary" tab, but may remain on the map if they occur on the same spot as coins of the approp. metal

### ISSUE THREAD

**Issue by pyzmark** [leemordechai/FLAME#54]
If I try to filter for gold coins but two finds appear on the same spot, it appears that the coin finds with non-gold coins are retained, as in the photo attached. See how there are bronze coins there? The find underneath it has only gold coins, though, so I assume that is why it passed through the filter. When you open the summary of groups, however, the bronze groups seem not to appear. But they really should not appear on the map either.

![image](https://user-images.githubusercontent.com/28210739/193976773-c5c299ea-e059-42f8-a90a-fd550c3b93c5.png)

**Comment by leemordechai** [comment]
raised to developer

**Comment by leemordechai** [comment]
Fixed & closing.
