### ISSUE TITLE
Coin groups not registering on map interface for Zemlyanoe gorodishe

### ISSUE THREAD

**Issue by pyzmark** [leemordechai/FLAME#56]
See video

https://user-images.githubusercontent.com/28210739/196996286-36417861-bbba-4b86-874d-c2d5f631a6bb.mp4

**Comment by leemordechai** [comment]
@pyzmark The issue here is that these coins are later than 750 so we don't show them in the app at all (but they do appear in the JSON): 
![image](https://user-images.githubusercontent.com/16713928/201356237-9a6f02ab-b9a9-45f1-b306-a853dbd91bff.png)


Please respond or close this issue.
