### ISSUE TITLE
"Buggy hoard" cannot be deleted

### ISSUE THREAD

**Issue by pyzmark** [leemordechai/FLAME#6]
No luck deleting this dummy hoard (called "Buggy Hoard"). I successfully created and deleted another dummy hoard just now called the "Tester Hoard".
[http://csla100w.princeton.edu:83/CoinFindings/Edit/9504?returnUrl=http%3A%2F%2Fcsla100w.princeton.edu%3A83%2FCoinFindings%2FPreview%3Fgrid-filter%3Dcf_name__3__buggy](http://csla100w.princeton.edu:83/CoinFindings/Edit/9504?returnUrl=http%3A%2F%2Fcsla100w.princeton.edu%3A83%2FCoinFindings%2FPreview%3Fgrid-filter%3Dcf_name__3__buggy)
![image](https://user-images.githubusercontent.com/28210739/113204329-6bcfe300-922a-11eb-9096-1d2e907227c2.png)

**Comment by leemordechai** [comment]
raised to developer

**Comment by leemordechai** [comment]
this has been resolved and I've deleted the entry
