### ISSUE TITLE
Error when I try to delete a denomination

### ISSUE THREAD

**Issue by pyzmark** [leemordechai/FLAME#63]
I tried to deleted the denomination "2.42g" and it errored, as below. Once solved, perhaps the other categories should be checked for the same problem. This is hard to test unless we add a number of dummy categories and try to delete them (and then, if affected, those will be hanging around until the problem is solved...). We should discuss whether we want to do that.

<img width="820" alt="image" src="https://user-images.githubusercontent.com/28210739/210416459-2ff02d4d-e0ed-4e5f-94ed-00a27f31c6ab.png">

**Comment by leemordechai** [comment]
The issue here is that we still have a few printruns with this denomination in FLAME's minting phase - once we rename those the we'll be able to delete the denomination.

**Comment by leemordechai** [comment]
@pyzmark @IliaCurtoPelle closing this for now.
