### ISSUE TITLE
Error creating Elauissa-Sebaste find

### ISSUE THREAD

**Issue by ilia-curtopelle** [leemordechai/FLAME#65]
I tried inputting the data as it appears in the pictures attached but I got an error message that prevents me from creating a record for this location )
![Untitled1](https://github.com/leemordechai/FLAME/assets/117390632/da27b1cf-d332-43f8-98bc-ea93ea936209)
![Untitled2](https://github.com/leemordechai/FLAME/assets/117390632/33d08a3f-bac1-437d-88f0-2210ac3cc0a4)
![Untitled](https://github.com/leemordechai/FLAME/assets/117390632/1ab27eac-a1e1-468d-9528-431d0215e34f)

**Comment by leemordechai** [comment]
Not sure what the deal was but I was able to create finds without problems, so closing this for now - please repoen if there's still an issue on your side.
