### ISSUE TITLE
"External data" button does not show up for individual finds that lack data

### ISSUE THREAD

**Issue by pyzmark** [leemordechai/FLAME#7]
If you search for it on its own, the following entry shows no data: PAS: Bancroft Roman Villa 2926. It does appear on the map as a red dot.

![image](https://user-images.githubusercontent.com/28210739/113603924-cb9b0500-9601-11eb-91bc-108ac6ffad55.png)

However, when you search for it alongside other finds, an "external data" button shows up (see below), which takes you to the PAS site and to the exact entry.

![image](https://user-images.githubusercontent.com/28210739/113604221-31878c80-9602-11eb-9542-c0d0a0bb6110.png)

This button does not appear when you try to search for PAS 2926 by itself—if not a bug, then it might be worth deliberately putting in the "external data" button for single entries, even ones lacking data. 

This link takes you here, are you can see that this entry has content, which has not been imported properly, for some reason (though this is covered in Issue #2, and so isn't the point here): [https://finds.org.uk/database/hoards/record/id/2926](url)

**Comment by leemordechai** [comment]
raised to the developer

**Comment by leemordechai** [comment]
this should be fixed now - all PAS finds should have the 'External Data' button.

**Comment by pyzmark** [comment]
This is fixed, I can confirm. In addition to an "external data" button, perhaps keeping a "coin groups" button would be good, and the option to export data. These two are still missing.

**Comment by leemordechai** [comment]
Raised to developer

**Comment by leemordechai** [comment]
Fixed - and kept both the buttons you mentioned (see image)
![image](https://user-images.githubusercontent.com/16713928/116237827-5d151700-a769-11eb-8c12-ef5622965795.png)
