### ISSUE TITLE
Producing mint+metal groupings in Summary yields error

### ISSUE THREAD

**Issue by pyzmark** [leemordechai/FLAME#9]
The video (apologies for audio echo) shows the process of trying to use Tools to create a Summary and then group it by Mint & Metal. It fails on two different mints.

https://user-images.githubusercontent.com/28210739/115821040-46646e00-a3bf-11eb-966c-9eeb8efd6e64.mp4

**Comment by leemordechai** [comment]
Thanks! Raised to developer.

**Comment by leemordechai** [comment]
Fixed!
